spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jamesgrice30
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true